csgo_guide/urls.py
from django.contrib import admin
from django.urls import path
from register import views
from players.views import home
from django.urls import include
from register import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home.as_view(),name="home"),
    path('register/',include('register.urls'))
]

register/urls.py
from django.urls import path
from .views import  signup,getin,userout

app_name = 'register'

urlpatterns = [
    path('',getin,name='login'),
    path('signup',signup,name='signup'),
    path('logout',userout,name='logout'),
]

players/models.py
from django.db import models

# Create your models here.


class player(models.Model):
    name = models.CharField(max_length=50)
    history = models.TextField()
    image = models.ImageField(upload_to='player_image')

register/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional in user
    profile_pic = models.ImageField(upload_to='profile_pic')
    bday=models.DateField(auto_now=False)

    def __str__(self):
        return self.user.first_name

players/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import player
# Create your views here.


class home(ListView):
    model = player
    

register/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from .models import Profile
from django.contrib.auth.decorators import login_required
# Create your views here.




@login_required
def userout(request):
    logout(request)
    return redirect('register:login')

    return render(request,'home.html')


def getin(request):
    if request.method=="POST":
        username= request.POST.get("uname")
        password = request.POST.get("password")
        user = authenticate(username=username,password=password)

        if user is not None:
            login(request,user)
            return redirect('players:home')
        
        else:
            return render(request,'login.html',{'error':'Username and Password not matching! Try again!'})
    
    else:
        return render(request,'login.html')






def signup(request):
    if request.method == "POST":
        fname = request.POST.get('fname') 
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        password1=request.POST.get('password1')
        password2=request.POST.get('password2')
        image = request.POST.get('image')
        bod = request.POST.get('bod')
        uname = request.POST.get('uname')

        if password1 == password2 :
            try:
                user= User.objects.get(username=uname)
                return render(request,'form.html',{'error':"This Username is already taken!"})
            except User.DoesNotExist:
                user = User.objects.create_user(username=uname,password=password1,first_name=fname,last_name=lname,email=email)
                user.save()
                profile = Profile(profile_pic=image,bday=bod,user=user)
                profile.save()
                login(request,user)
                return redirect('players:home')
        else:
            return render(request,'form.html',{'error':'Your Password did not matched!'})
    
        
    
    return render(request,'form.html')

players/templates/player_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<img src="{% static 'images/home_bg.jpg' %}" alt="bg" class="img-fluid" style="width: 100%; height: 200px; padding-top: 30px;">

<div class="row">
    <div class="col-4">
        

    </div>



</div>


{% endblock %}

register/templates/form.html
{% extends 'base.html' %}

{% block content %}

    <div class="container form">
        {% if error %}
        <p style="color: red;">*{{ error }}</p>
        {% endif %}
        <form action="{% url 'signup' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
    
            <div class="form-group">
                <label for="FName">First Name</label>
                <input type="text" class="form-control" id="FName" placeholder="Your sweet Name" name="fname">
            </div>
            <div class="form-group">
                <label for="LName">Last Name</label>
                <input type="text" class="form-control" id="LName" placeholder="If you have one" name="lname">
            </div>
            <div class="form-group">
                <label for="Email">Email</label>
                <input type="email" class="form-control" id="Email" placeholder="Email" name="email">
            </div>
            <div class="form-group">
                <label for="uname">Username</label>
                <input type="text" class="form-control" id="uname" placeholder="choose cool username" name="uname">
            </div>
            <div class="form-group">
                <label for="Password">Password</label>
                <input type="password" class="form-control" id="Password" placeholder="Choose smartly" name="password1">
            </div>
            <div class="form-group">
                <label for="Password1">Confirm Password</label>
                <input type="password" class="form-control" id="Password1" placeholder="Make sure you dont copy" name="password2">
            </div>
            <div class="form-group">
                <label for="date">Birth Date</label>
                <input type="date" class="form-control" id="date" name="bod">
            </div>
            <div class="form-group">
                <label for="image">Profile</label>
                <input type="file" class="form-control-file" id="image" name="profile">
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="LETS' GO">

            </div>
    
    
    
    
        </form>
    

    </div>
    


{% endblock %}

register/templates/login.html
{% extends 'base.html' %}
{% block content %}

<div class="container login">
    {% if error %}
    <p style="color: red;">*{{error}}</p>
    {% endif %}
    

    <form action="{% url 'register:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="uname">Username</label>
            <input type="text" class="form-control" id="uname" placeholder="username" name="uname">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" placeholder="password" name="password">
        </div>
        <div class="form-group">
            <input type="submit" value="LOGIN!" class="btn btn-primary">

        </div>
    </form>

</div>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
    <meta lang="en" charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/master.css'%}">


</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <a class="navbar-brand" href="#">CSGO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">NEWS<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">UPDATE</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">GUN GUIDE</a>
            </li>
          </ul>
        </div>
        {% if user.is_authenticated %}
        <a href="{% url 'register:logout' %}" style="float: right;" ><button class="btn btn-primary " style="float: right;">LOGOUT</button></a>
        {% else %}
        <a href="{% url 'register:login' %}" style="float: right;" ><button class="btn btn-primary " style="float: right;">LOGIN</button></a>
        <a href="{% url 'register:signup' %}" style="float: right;" ><button class="btn btn-primary " style="float: right;">SIGNUP</button></a>
        {% endif %}
      </nav>

    {% block content%}
    {% endblock %}


</body>
</html>